### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by Webysther**
Lowercase name correction.

### CODE REVIEW

**Comment by niemyjski** [comment]
The file name is `tracekit.js`. Can you change it from `traceKit.js` to `tracekit.js`

**Comment by niemyjski** [comment]
Also, could you please check the package.json file as well for the correct name.

**Comment by Webysther** [comment]
Yes, the package.json sounds good. Using bower to automate because the name its fail.

**Comment by niemyjski** [comment]
Thanks for the commit. Do you need me to do a new minor release?

**Comment by niemyjski** [comment]
I've pushed 0.2.1 ( https://github.com/csnover/TraceKit/releases/tag/v0.2.1 )

**Pull request merged**
