### PR TITLE
Expose getSource as TraceKit.getSource

### PR DESCRIPTION
**Pull request by rwhogg**
This is identical to https://github.com/rhoggSugarcrm/TraceKit/commit/1beb3451fe003c421a209f8317321291dced09b2, just applied to a different repo.

Please <b>do not merge</b> yet, I probably want to write a test or two.

### CODE REVIEW

**Comment by rwhogg** [comment]
One other thing - I've also got to update the TypeScript module definition to reflect the new interface. This might take me a bit, since I don't use TypeScript, but I'll see what I can do tomorrow.

**Comment by niemyjski** [comment]
Okay, I was wanting to create some jasmine tests in the root of the project (TraceKit-spec.js). Would you mind setting this up? Just let me know when you want me to commit this.

**Comment by niemyjski** [comment]
Also for others looking at this change... This makes it easier to integrate with source maps... as your sharing the source cache.

**Comment by rwhogg** [comment]
@niemyjski - sure, I can try and set up Jasmine in the root folder later today.

**Comment by niemyjski** [comment]
Thanks!

On 5/24/15, Bob Hogg <notifications@github.com> wrote:
> @niemyjski - sure, I can try and set up Jasmine in the root folder later
> today.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/csnover/TraceKit/pull/15#issuecomment-105021393


-- 
Thanks
-Blake Niemyjski

**Comment by rwhogg** [comment]
@niemyjski I made https://github.com/csnover/TraceKit/pull/19 to address adding the test suite.

The one thing: there are some existing Mocha tests. What do you want to do with them?

**Comment by niemyjski** [comment]
If possible port the one test over and then remove the test folder 

Sent from Outlook




On Sun, May 24, 2015 at 3:33 PM -0700, "Bob Hogg" <notifications@github.com> wrote:












@niemyjski I made #19 to address adding the test suite.



The one thing: there are some existing Mocha tests. What do you want to do with them?

**Comment by rwhogg** [comment]
I tried porting it and it runs, but I'm not really sure what to do with it. I've never used Jasmine before, so I'm not sure what the equivalent of interceptMochaRunner is (if it even exists).

@niemyjski would you mind handling that yourself? I apologize, but I don't have a lot of time to commit to this right now. #19 now includes browser support for Jasmine, so I think it might be good to merge that and deal with this later (if at all).

**Comment by niemyjski** [comment]
Yeah I'll merge it when I get to a pc, is this pr ready?

**Comment by rwhogg** [comment]
Yes, this PR is now ready. I updated the TypeScript module declaration but did not write a test; as it turns out it did not really seem necessary.

Thank you very much for your assistance.

**Pull request merged**
